### ISSUE TITLE
Enable Mr. X "2x" move

### ISSUE THREAD

**Issue by neaprabhu** [azharkhan/scotland-yard#6]
The current implementation of the game does not give Mr X an option to make the 2x move. Need to enable functionality as well as the UI update to visually display this item on the webpage

**Comment by azharkhan** [comment]
thanks for filing this - this  should've been fixed with: https://github.com/azharkhan/scotland-yard/commit/63bd6b67c046c1b96bb0bca6f7a8673689a58291
