### ISSUE TITLE
Feature Request: When detectives are at same position/station, somehow display their circles so that each indicator can be seen

### ISSUE THREAD

**Issue by neaprabhu** [azharkhan/scotland-yard#7]
With the current implementation of the game, for eg:, if 2 detectives land at the same station, the circles/indicator will align one on top of the other and hence only 1 circle can be visually seen on the map. If there is a way to somehow highlight both circles that will help show that there is more than one detective currently at the station. Just a visual element that will help.

**Comment by azharkhan** [comment]
closing this since as per the rules and #13 - detectives cannot be on the same location at the same time.
